name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_data_processing_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: node --version
      - name: Print ОС version
        run: |
          echo "Linux Version:" && uname -a

  check_database_version:
    runs-on: ubuntu-latest
    steps:
      - name: Print SQLite version
        run: sqlite3 --version
      - name: Виведення версії ОС
        run: |
          echo "Linux Version:" && uname -a
