name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  PrintDataProcessingVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: node --version
      - name: Print ОS Linux version
        run: uname -a

  PrintDatabaseVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print SQLite version
        run: sqlite3 --version
      - name: Print ОS Linux version
        run: uname -a
